name: fluster
description: A geospatial point clustering library for Dart.
version: 1.0.0
homepage: https://happeningsoft.com
author: Alfonso Cejudo <fonz@happeningsoft.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  meta: ^1.1.7

dev_dependencies:
  pedantic: ^1.7.0
  mockito: ^4.1.0
  test: ^1.6.0
